project:
  type: website

website:
  title: "Rhian Davies"
  navbar:
    background: secondary
    logo: "img/letter-R.png"
    logo-alt: "A handwritten, blue, letter R"
    right:
      - text: "About"
        file: index.qmd
      - talks.qmd
      - projects.qmd

format:
  html:
    theme: theme.scss
